version: '3.7'

services:
  app:
    container_name: frontend
    image: non/frontend
    restart: always
    build: ./frontend
    ports: ['8080:8080']
  back:
    container_name: backend
    image: non/backend
    restart: always
    build: ./backend
    ports: ['3000:3000']
  
